// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2raKQfPhEprRifyxXhMOcoNoCLYghtFY',
    appId: '1:904209210324:web:a5ccedae77f24d20561441',
    messagingSenderId: '904209210324',
    projectId: 'finalyyearproject',
    authDomain: 'finalyyearproject.firebaseapp.com',
    storageBucket: 'finalyyearproject.appspot.com',
    measurementId: 'G-FBX6XG6TN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmiD1zhYy9uGaPtuQyRo_k6_1lE5L5Ho',
    appId: '1:904209210324:android:20992ebdda3d099f561441',
    messagingSenderId: '904209210324',
    projectId: 'finalyyearproject',
    storageBucket: 'finalyyearproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7SeKeX5f4marPSMCr2g6edvvo7s5Bv0',
    appId: '1:904209210324:ios:cab474ce19bf1460561441',
    messagingSenderId: '904209210324',
    projectId: 'finalyyearproject',
    storageBucket: 'finalyyearproject.appspot.com',
    iosBundleId: 'com.example.mlToolkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7SeKeX5f4marPSMCr2g6edvvo7s5Bv0',
    appId: '1:904209210324:ios:cab474ce19bf1460561441',
    messagingSenderId: '904209210324',
    projectId: 'finalyyearproject',
    storageBucket: 'finalyyearproject.appspot.com',
    iosBundleId: 'com.example.mlToolkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2raKQfPhEprRifyxXhMOcoNoCLYghtFY',
    appId: '1:904209210324:web:93ff01c3c0bb9117561441',
    messagingSenderId: '904209210324',
    projectId: 'finalyyearproject',
    authDomain: 'finalyyearproject.firebaseapp.com',
    storageBucket: 'finalyyearproject.appspot.com',
    measurementId: 'G-J255K6C5S5',
  );
}
